#!/bin/bash

cd ~/tbot

arrayCrypto=("BTC/USDT" "ETH/USDT" "BNB/USDT" "XRP/USDT" "ADA/USDT" "SOL/USDT" "DOGE/USDT" "DOT/USDT" "SHIB/USDT" "MATIC/USDT" "TRX/USDT" "AVAX/USDT" "UNI/USDT" "ATOM/USDT" "ETC/USDT" "LINK/USDT" "LTC/USDT" "FTT/USDT" "NEAR/USDT" "XLM/USDT" "ALGO/USDT" "BCH/USDT" "APE/USDT" "FLOW/USDT" "VET/USDT" "FIL/USDT" "ICP/USDT" "QNT/USDT" "CHZ/USDT" "HBAR/USDT" "XTZ/USDT" "SAND/USDT" "MANA/USDT" "EOS/USDT" "AXS/USDT" "THETA/USDT" "EGLD/USDT" "AAVE/USDT" "LDO/USDT" "IOTA/USDT" "XEC/USDT" "BTTC/USDT" "GRT/USDT" "ZEC/USDT" "CAKE/USDT" "MKR/USDT" "KLAY/USDT" "NEO/USDT" "HNT/USDT" "SNX/USDT" "FTM/USDT" "NEXO/USDT" "PAXG/USDT" "RUNE/USDT" "ZIL/USDT" "ENJ/USDT" "AR/USDT" "BAT/USDT" "DASH/USDT" "RVN/USDT" "STX/USDT" "COMP/USDT" "KAVA/USDT" "WAVES/USDT" "TWT/USDT" "AMP/USDT" "GMT/USDT" "LRC/USDT" "KSM/USDT" "BTG/USDT" "HOT/USDT" "CELO/USDT" "ENS/USDT" "XEM/USDT" "XEM/USDT" "DCR/USDT" "CRV/USDT" "MINA/USDT" "POWR/USDT")

for crypto in ${arrayCrypto[@]}; do
        echo "\n**** Crypto being passed in is $crypto"
        node buy-order-macd $crypto
        sleep 5
done
